# Generated by Django 5.2.3 on 2025-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatitasFelices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('veterinaria', 'Atención veterinaria'), ('cirugia', 'Cirugía'), ('imagenes', 'Imágenes'), ('peluqueria', 'Peluquería')], max_length=30)),
            ],
        ),
    ]
