# Generated by Django 5.2.3 on 2025-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatitasFelices', '0002_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='animal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='edad_mascota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
