# Generated by Django 5.2.2 on 2025-06-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatitasFelices', '0004_imagenproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
